
experiment:
  name: 'NSGA2_testrun'
  num_inputs: 20
  num_outputs: 5
  n_hidden_neurons: 10
  enemy_groups:
    - [1, 2, 6, 7]
    - [2, 4, 5, 7, 8]
  pop_size: 50
  n_gen: 20
  cxpb: 0.7
  mutpb: 0.05
  tournament_size: 3
  elitism_rate: 0.05
  random_seed: 42
  selection_method: 'NSGA2'  # Options: 'NSGA2', 'Tournament', 'DeterministicCrowding'


parallel:
  enable: true
  processes: 'max'  # Number of parallel processes for evaluations
  reserved_cores: 2 # Number of reserved cores for your pc to run
  multiple_runs: 2  # Number of independent evolutionary runs

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: simple
      filename: 'experiment.log'
  loggers:
    evolutionary_algorithm:
      level: INFO
      handlers: [console, file]
      propagate: no
  root:
    level: INFO
    handlers: [console]

